feat: :sparkles: cca usergroup initial code
biodiv-platform/cca-ui pull request #25
Opened 2023-10-26 09:57 UTC by arunasd463

2024-01-03 13:28 UTC, prakhar-s requested changes

2024-01-03 13:28 UTC, prakhar-s commented on src/pages/group/[groupName]/user/download-logs.tsx
do we need user download logs in CCA?

2024-01-03 13:28 UTC, prakhar-s commented on yarn.lock
Just verify that we don't install unnecessary  dependencies and the versions don't cause conflicts.

2024-01-04 03:47 UTC, arunasd463 commented on src/components/@core/activity/activity-types.ts
> +  UNFEATURED: "UnFeatured"
Its used as a conditional check in ContentBox . we need it .

2024-01-04 04:02 UTC, arunasd463 commented on src/components/@core/table/index.tsx
There was an extra property called getCheckboxProps , added it and resused existing property .

2024-01-04 04:08 UTC, arunasd463 commented on src/pages/group/[groupName]/user/download-logs.tsx
yes we have download logs in cca.

2024-01-04 04:20 UTC, arunasd463 commented on src/components/pages/group/edit/form.tsx
> +        habitatId: Yup.array().required(),
not able to remove this , backend requires this .

2024-01-04 10:12 UTC, prakhar-s approved these changes

2024-01-04 10:12 UTC, merged