feat: :sparkles: tinymce image wrap and pages updates
biodiv-platform/cca-ui pull request #35
Opened 2024-02-15 05:47 UTC by arunasd463

2024-02-22 15:10 UTC, prakhar-s requested changes
verify lock file changes once

2024-02-23 03:52 UTC, arunasd463 commented on src/configs/site-config.example.js
I added this for development purpose , its not needed in deployment.

2024-02-23 03:54 UTC, arunasd463 commented on src/styles/page.scss
> +.epc {
This class is created by harsh for cropcert , it will be easy to reuse it .

2024-02-23 03:55 UTC, arunasd463 commented on src/utils/pages.ts
> +      <a href="${href}" rel="noopener noreferrer" class="epc" id="${id}">
No we cant use chakra elements here.

2024-02-23 03:55 UTC, arunasd463 commented on src/utils/pages.ts
> +    const href = /<a[\s\S]*?href=["']([^"]+)["'][\s\S]*?>/g.exec(v)?.[1];
This is done by harsh , its working fine .

2024-02-23 06:50 UTC, prakhar-s commented on src/configs/site-config.example.js
Ok. Then you should remove these from the commits. Shouldn't go into master

2024-02-23 07:39 UTC, arunasd463 commented on src/configs/site-config.example.js
It already present in site-config of production , so adding it in site-config-example.

2024-02-23 07:42 UTC, prakhar-s approved these changes

2024-02-23 07:59 UTC, merged